services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - sales-network

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
    ports:
      - "3306:3306"
    networks:
      - sales-network
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      retries: 3

  discovery-server:
    build:
      context: ./discovery-server
    ports:
      - "8761:8761"
    networks:
      - sales-network

  order-service:
    build:
      context: ./order-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/order_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=mysecretpassword
      - eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq
      - grpc.client.stockService.address=static://inventory-service:9090
      - SPRING_RABBITMQ_PORT=5672
    depends_on:
      - mysql
      - rabbitmq
      - discovery-server
    networks:
      - sales-network

  inventory-service:
    build:
      context: ./inventory-service
    ports:
      - "8083:8083"
      - "9090:9090"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/inventorydb
      - eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
    depends_on:
      - mongo
      - rabbitmq
      - discovery-server
    networks:
      - sales-network

  payment-service:
    build:
      context: ./payment-service
    ports:
      - "8087:8087"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/payment_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=mysecretpassword
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
    depends_on:
      - mysql
      - rabbitmq
      - discovery-server
    networks:
      - sales-network

  catalog-service:
    build:
      context: ./catalog-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/catalog_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=mysecretpassword
      - eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - grpc.client.stockService.address=static://inventory-service:9090
    depends_on:
      - mysql
      - redis
      - rabbitmq
      - discovery-server
    networks:
      - sales-network

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
    networks:
      - sales-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - sales-network

networks:
  sales-network:
    driver: bridge
volumes:
  mysql-data:
  mongo-data: